### ISSUE TITLE
Unable to import august.api

### ISSUE THREAD

**Issue by akmalhakimi1991** [snjoetw/py-august#14]
Hi there. I tried the sample usage code and unable to get it to work. This line: 
`from august.api import Api `

return this error:

>   File "\<stdin\>", line 1, in \<module\>
>   File "C:\Python27\lib\site-packages\august\api.py", line 101
>     http_session: Session = None):

Note that I tested this in `v0.7.0`. However, this error didn't happen in `v0.6.0`

**Comment by ehendrix23** [comment]
What version of Python do you have installed?

**Comment by snjoetw** [comment]
Close as there's no response, highly likely it's due to incorrect python version
