### ISSUE TITLE
SyntaxError: non-default argument follows default argument

### ISSUE THREAD

**Issue by itsmemukesh21** [snjoetw/py-august#18]
Traceback (most recent call last):
  File "aug.py", line 1, in <module>
    from august.api import Api
  File "/home/inxenuity/py-august/august/api.py", line 100
    def __init__(self, timeout=10, command_timeout=60,http_session,Session = None):
                    ^
SyntaxError: non-default argument follows default argument

this error is occured in the api.py file

**Comment by snjoetw** [comment]
Can you confirm the version of your python?

**Comment by snjoetw** [comment]
Closing this as this is most likely due to incorrect python version being used
