### ISSUE TITLE
stand alone configuration?

### ISSUE THREAD

**Issue by dikodahan** [snjoetw/py-august#20]
Can you please share some details on how can this be used as a stand alone configuration?
It seems like this is only meant for Home Assistant and is (maybe) missing a file/s and some information on how can this be run outside of HA.
Your help is much appreciated!

**Comment by snjoetw** [comment]
Check the usage section: https://github.com/snjoetw/py-august#usage
You should be able to run it without HomeAssistant, let me know if you have problem running it
